### ISSUE TITLE
Right column should be smaller (?)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboardv2#191]
... or whatever it takes to get more image on the screen

![image](https://user-images.githubusercontent.com/5648894/68206080-c2000e80-ffc3-11e9-9abf-e2063a7a52dc.png)

**Comment by marcoherbst** [comment]
and the timestamp below the image should be 1 line (not 2) and more readable

2019-11-05T11:57:59+00:00

**Comment by JaviCT** [comment]
The timestamp is now fixed

**Comment by marcoherbst** [comment]
Closing as it's a duplicate:
https://github.com/evercam/evercam-dashboardv2/issues/184
