### ISSUE TITLE
Internet Explorer 10+ ....

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboardv2#245]
@affan00 
- [x] Buttons not displayed on Live View
- [x] Recording tab rendered but the content is showed transparent or semi-transparent
- [x] Archives tab: wrong aspect ratio
- [x] Sigin page: Background video not showing and the position is wrong.

**Comment by JaviCT** [comment]
#247

**Comment by affan00** [comment]
It's done, I am closing this issue.
