### ISSUE TITLE
Pasting an email address

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboardv2#290]
I pasted an email address copied from Google in the format:

FirstName LastName <firstlast@domain.com>

.... it turned it into 3 invalid emails.

When I do the same in Gmail, it auto-corrects. Can we?

-----------

When I manually fixed the problem by deleting all 3 and pasting in a valid email, it still showed me an error, but I was able to submit. This whole process is a bit shakey.

**Comment by marcoherbst** [comment]
@affan00  , I think @JaviCT has done this? (he showed it to me on Friday)

**Comment by JaviCT** [comment]
@affan00 this is the function that is reading the emails when you paste something and prevent the default behaviour: https://github.com/evercam/evercam-dashboardv2/blob/03d2d943b75d8326e95b78637eeaf95d2887e2ae/components/shared/Combobox.vue#L82

**Comment by marcoherbst** [comment]
Sorry guys, I can't replicate this. It's something different when i COPY from an email field in Gmail. Anyhow, I'll close this task for now.
