### ISSUE TITLE
/Settings page layout & text

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboardv2#304]
![image](https://user-images.githubusercontent.com/5648894/70132765-c11ed300-167c-11ea-85d3-0d5c6717a18c.png)

Remove the sentence about Gravatar, it's not important.

Remove Hide Offline Cameras option (always on).

Responsiveness is not quite right.

I think this page (and others, like Archives) needs to reconsider the "Back" button. This one has none. The Archvies page one has one, but it's in the wrong place.  Maybe it needs to replace the tabs. Open for suggestions.

**Comment by affan00** [comment]
It's done, I am closing this issue.
