### ISSUE TITLE
Compare tab improvements

### ISSUE THREAD

**Issue by JaviCT** [evercam/evercam-dashboardv2#325]
- [x] Logo size in compare tab on small resolution screens

![image](https://user-images.githubusercontent.com/19703794/70338427-d3e40400-1844-11ea-96e0-abcb5e0fdfb0.png)

- [x] "Share / Download / Embed" button overlap left menu and calendar on small resolution screens

![image](https://user-images.githubusercontent.com/19703794/70338473-e9f1c480-1844-11ea-93c3-7ebee8ecbb91.png)
![image](https://user-images.githubusercontent.com/19703794/70338627-28877f00-1845-11ea-82f4-86bbc8726f40.png)

**Comment by affan00** [comment]
It's done, I am closing this now.
