### ISSUE TITLE
Unable to delete the user account.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-dashboardv2#373]
I've tried to delete the account nothing happened. 
You can follow these steps to reproduce this error.
Go to settings -> Delete the account -> it will take you to the good bye page -> go to login page -> type deleted account username and password -> it will log in again.

**Comment by ijunaid8989** [comment]
It may be related to this work https://github.com/evercam/evercam-server/pull/1213

@JaviCT haven't updated the models yet?

**Comment by ijunaid8989** [comment]
its done. and tested.
