### ISSUE TITLE
Stephens Green /Archives

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-dashboardv2#447]
https://dash.evercam.io/v2/cameras/stephens-green/archives

+ 3 Broken Thumbnails.
+ When I have 3 accross, it leaves space for 2 more archives at the bottom and asks me to "load more" before loading them. That's a bit silly.

**Comment by azharmalik3** [comment]
Archives paging fixed and created an issue #501 for broken thumbnails.
