### ISSUE TITLE
Improve the meta tags

### ISSUE THREAD

**Issue by JaviCT** [evercam/evercam-dashboardv2#76]
![image](https://user-images.githubusercontent.com/19703794/65702133-62384e80-e07a-11e9-8dc3-187d9f8946d7.png)

**Comment by marcoherbst** [comment]
@JaviCT I will ask for this before Golive actually, if possible. And please consider all possible metatags, not only Title.

**Comment by JaviCT** [comment]
It is done, I am closing this

**Comment by JaviCT** [comment]
@marcoherbst I added these tags: title, lang: en, description, og:type, og:url, og:title, og:description, og: image, twitter:card, twitter: url, twitter:title, twitter: description, twitter: image

**Comment by marcoherbst** [comment]
Excellent. Good stuff.
